# Generated by Django 5.2.5 on 2025-08-11 17:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='email',
            new_name='student_email',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='code',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='code_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverification',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('signup', 'signup')], default='signup', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
